language: cpp
compiler: gcc
dist: trusty
sudo: false

before_install:
  # Get a recent catch release
  - mkdir -p ~/catch/single_include/
  - wget -P ~/catch/single_include/ https://github.com/philsquared/Catch/releases/download/v2.0.0-develop.4/catch.hpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:beineri/opt-qt593-trusty'
    packages:
      - g++-7
      - qt59-meta-minimal
      - qt59creator
      - qt59charts-no-lgpl
      - xvfb

script:
  # Set up Qt
  - source /opt/qt59/bin/qt59-env.sh
  # Compile debug build
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake -D CATCH_DIR="~/catch" -D CMAKE_BUILD_TYPE=Debug .
  - cmake --build . -- -j2
  # Run tests
  - xvfb-run -a -e xvfb.log core/test/novelist_core_test
  - xvfb-run -a -e xvfb.log plugins/novelist_stats_test

env:
  global:
    secure: I2sM0SNeZpuTIA3NQuBnETCNOj/wpfaLfUAD0+HKvYi+7MTCN9//+tU4v1zWbxZNr9YZ5k2jtlP3LAFpdHiJF/N5oWSe6bwrkbC3VzvrbgPKTUjfqufJABnnfhidyDYAlM9fhxl/XvldPQMNTUnvEEFW/O5iaUy504Bzu2XIpXaoS27R+zSVC8o2Z7USGoXfu4lsiOvzUjJnim/KtOIFxkwqnIJY3Q+vUu/W2/yNObfY88K9buKAuxuPcyJi/r/+P99NcUTBHT9r42Yuhs5jqBKQS69Eq5LrDRPhxIVIaSFU7hF6rDSB2JM9jGDN3V3+8IqCbjhh19uQRm4AbNa37/uOP0smi0tHVHJO2ZutE2qH+hU2VefjuDQogsVyeoMlnKmWVtoz3IDE0J6Y97etrXSs1PavTLR7+a4G9Jbv5DNvzprJZT5HoKhmkmOpvJPhLJGB/chgSsiq/GhbhgTcGl5OKE1Y4S9igrevm8rEA7P7dHLqRZlPe7KpEKbuTkqHQubgFZEh1k3PAZ8oSeFfNL7UY5Z9yodBMkiuq/rfRM2c2BYoATHoKwkJ256kUyjiQ9WVKZZzjgLsJIEOUoeAuuBimT4L0hcmKteGPQQC1Pl/pfaHb+F87wmMFxI0dkrVrVm1t9dpSgcyUyWpl3RyL4SL5q7OwUN9XWjCpwMeT1A=

# Don't clone git lfs files for CI
# Reason: Travis clone is run unauthenticated on a free plan and thus runs into the GitHub API rate limit
# Also see https://github.com/concept-to-clinic/concept-to-clinic/issues/69
git:
  lfs_skip_smudge: true