
option(ASAN "Enable gcc address sanitizer" OFF)
if (ASAN)
    set (CMAKE_CXX_FLAGS "-fsanitize=address")
endif()
option(LSAN "Enable gcc leak sanitizer" OFF)
if (LSAN)
    set (CMAKE_CXX_FLAGS "-fsanitize=leak")
endif()
option(TSAN "Enable gcc thread sanitizer" OFF)
if (TSAN)
    set (CMAKE_CXX_FLAGS "-fsanitize=thread")
endif()
option(USAN "Enable gcc undefined sanitizer" OFF)
if (USAN)
    set (CMAKE_CXX_FLAGS "-fsanitize=undefined")
endif()

option(TESTS "Build unit tests" ON)